import { Html, Head, Main, NextScript } from "next/document"
import React from "react"

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Wolf Manager - frente de caixa</title>
        <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Montserrat:wght@300;400;500;700&display=swap" rel="Document" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
